services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:lts
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lvc
      - MYSQL_DATABASE=chat
      - MYSQL_USER=lvc
      - MYSQL_PASSWORD=lvc123
